export const ROUTES = {
    HOME: "/",
    MENU: "/menu",
    SIGN_IN: "/sign-in",
    SIGN_UP: "/sign-up",
    CART: "/cart",
    PAYMENT: "/payment",
    MEALS_ADMIN: "/mealsAdmin",
    ADD_MEALS: "/addMeals",
    CARDPAYMENT: "/cardpayment",
    CUSTOMER_PROFILE: "/profile",
    RESET_PASSWORD : "/security",
    MYORDERS: "/orders",
    DASHBOARD_ADMIN : "/DashboardAdmin",
    CUSTOMER_FEEDBACK : "/feedback",
    LOGOUT_ADMIN : "/SignIn",
    ORDER : "/orders",
    ADMIN_FEEDBACK : "/adminFeedbacks",
    ADMIN_MEALREPORT : "/adminMealReports",
    CALORIE_REPORT: "/CalorieReport",
    REGISTRATION_REPORT: "/RegistrationReport",
    CUSTOMER_LIST: "/CustomersList",
    ADMIN_ORDERS: "/adminorders",
    ADMIN_PAYMENTS: "/adminPayments",
};
